services:
  postgres:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d bookstore" ]
      interval: 30s
      timeout: 10s
      retries: 5
